import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { Navbar } from "@/components/layout/Navbar";
import { AuthChecker } from "@/components/utils/AuthChecker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Patient Education Generator",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <ReduxProvider>
               <Navbar></Navbar>
               <AuthChecker>{children}</AuthChecker>{" "}
            </ReduxProvider>
         </body>
      </html>
   );
}
